[[main]]
  identifier = "serbia"
  name = "Serbia"
  url = "#"
  weight = 1

[[main]]
  identifier = "kopaonik"
  name = "Kopaonik"
  url = "/en/kopaonik/"
  parent = "serbia"
  weight = 1

[[main]]
  identifier = "about"
  name = "About"
  url = "/en/about/"
  weight = 2

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/en/contact/"
  weight = 3
