[[main]]
  identifier = "slovenia"
  name = "Словения"
  url = "/ru/slovenia/"
  weight = 1

[[main]]
  identifier = "bled"
  name = "Блед"
  url = "/ru/slovenia/bled/"
  parent = "slovenia"
  weight = 1

[[main]]
  identifier = "velenje"
  name = "Веленье"
  url = "/ru/slovenia/velenje/"
  parent = "slovenia"
  weight = 2

[[main]]
  identifier = "izola"
  name = "Изола"
  url = "/ru/slovenia/izola/"
  parent = "slovenia"
  weight = 3

[[main]]
  identifier = "koper"
  name = "Копер"
  url = "/ru/slovenia/koper/"
  parent = "slovenia"
  weight = 4

[[main]]
  identifier = "kranj"
  name = "Крань"
  url = "/ru/slovenia/kranj/"
  parent = "slovenia"
  weight = 5

[[main]]
  identifier = "kranjska-gora"
  name = "Краньска Гора"
  url = "/ru/slovenia/kranjska-gora/"
  parent = "slovenia"
  weight = 6

[[main]]
  identifier = "ljubljana"
  name = "Любляна"
  url = "/ru/slovenia/ljubljana/"
  parent = "slovenia"
  weight = 7

[[main]]
  identifier = "maribor"
  name = "Марибор"
  url = "/ru/slovenia/maribor/"
  parent = "slovenia"
  weight = 8

[[main]]
  identifier = "novo-mesto"
  name = "Ново Место"
  url = "/ru/slovenia/novo-mesto/"
  parent = "slovenia"
  weight = 9

[[main]]
  identifier = "piran"
  name = "Пиран"
  url = "/ru/slovenia/piran/"
  parent = "slovenia"
  weight = 10

[[main]]
  identifier = "portoroz"
  name = "Порторож"
  url = "/ru/slovenia/portoroz/"
  parent = "slovenia"
  weight = 11

[[main]]
  identifier = "ptuj"
  name = "Птуй"
  url = "/ru/slovenia/ptuj/"
  parent = "slovenia"
  weight = 12

[[main]]
  identifier = "celje"
  name = "Целе"
  url = "/ru/slovenia/celje/"
  parent = "slovenia"
  weight = 13

[[main]]
  identifier = "croatia"
  name = "Хорватия"
  url = "/ru/croatia/"
  weight = 2

[[main]]
  identifier = "varazdin"
  name = "Вараждин"
  url = "/ru/croatia/varazdin/"
  parent = "croatia"
  weight = 1

[[main]]
  identifier = "zagreb"
  name = "Загреб"
  url = "/ru/croatia/zagreb/"
  parent = "croatia"
  weight = 2

[[main]]
  identifier = "karlovac"
  name = "Карловац"
  url = "/ru/croatia/karlovac/"
  parent = "croatia"
  weight = 3

[[main]]
  identifier = "novigrad"
  name = "Новиград"
  url = "/ru/croatia/novigrad/"
  parent = "croatia"
  weight = 4

[[main]]
  identifier = "opatija"
  name = "Опатию"
  url = "/ru/croatia/opatija/"
  parent = "croatia"
  weight = 5

[[main]]
  identifier = "porec"
  name = "Пореч"
  url = "/ru/croatia/porec/"
  parent = "croatia"
  weight = 6

[[main]]
  identifier = "pula"
  name = "Пула"
  url = "/ru/croatia/pula/"
  parent = "croatia"
  weight = 7

[[main]]
  identifier = "rijeka"
  name = "Риека"
  url = "/ru/croatia/rijeka/"
  parent = "croatia"
  weight = 8

[[main]]
  identifier = "rovinj"
  name = "Ровинь"
  url = "/ru/croatia/rovinj/"
  parent = "croatia"
  weight = 9

[[main]]
  identifier = "umag"
  name = "Умаг"
  url = "/ru/croatia/umag/"
  parent = "croatia"
  weight = 10

[[main]]
  identifier = "serbia"
  name = "Сербия"
  url = "/ru/serbia/"
  weight = 3

[[main]]
  identifier = "kopaonik"
  name = "Копаоник"
  url = "/ru/serbia/kopaonik/"
  parent = "serbia"
  weight = 1

[[main]]
  identifier = "southern-shuttles"
  name = "Южные шаттлы"
  url = "/ru/southern-shuttles/"
  weight = 4

[[main]]
  identifier = "vranje"
  name = "Вранье"
  url = "/ru/southern-shuttles/vranje/"
  parent = "southern-shuttles"
  weight = 1

[[main]]
  identifier = "krusevac"
  name = "Крушевац"
  url = "/ru/southern-shuttles/krusevac/"
  parent = "southern-shuttles"
  weight = 2

[[main]]
  identifier = "leskovac"
  name = "Лесковац"
  url = "/ru/southern-shuttles/leskovac/"
  parent = "southern-shuttles"
  weight = 3

[[main]]
  identifier = "nis"
  name = "Ниш"
  url = "/ru/southern-shuttles/nis/"
  parent = "southern-shuttles"
  weight = 4

[[main]]
  identifier = "paracin"
  name = "Парачин"
  url = "/ru/southern-shuttles/paracin/"
  parent = "southern-shuttles"
  weight = 5

[[main]]
  identifier = "cuprija"
  name = "Чуприя"
  url = "/ru/southern-shuttles/cuprija/"
  parent = "southern-shuttles"
  weight = 6

[[main]]
  identifier = "jagodina"
  name = "Ягодина"
  url = "/ru/southern-shuttles/jagodina/"
  parent = "southern-shuttles"
  weight = 7

[[main]]
  identifier = "airport-shuttles"
  name = "Аэропорт шаттл"
  url = "/ru/airport-shuttles/"
  weight = 5

[[main]]
  identifier = "belgrade-nikola-tesla"
  name = "Белград (BEG)"
  url = "/ru/airport-shuttles/belgrade-nikola-tesla/"
  parent = "airport-shuttles"
  weight = 1

[[main]]
  identifier = "nis-constantine-the-great"
  name = "Ниш (INI)"
  url = "/ru/airport-shuttles/nis-constantine-the-great/"
  parent = "airport-shuttles"
  weight = 2

[[main]]
  identifier = "craiova"
  name = "Адвент Крайова"
  url = "/ru/craiova/"
  weight = 6

[[main]]
  identifier = "blog"
  name = "Блог"
  url = "/ru/blog/"
  weight = 7

[[main]]
  identifier = "about"
  name = "О нас"
  url = "/ru/about/"
  weight = 8

[[main]]
  identifier = "contact"
  name = "Контакты"
  url = "/ru/contact/"
  weight = 9