[[main]]
  identifier = "serbia"
  name = "Сербия"
  url = "#"
  weight = 1

[[main]]
  identifier = "kopaonik"
  name = "Копаоник"
  url = "/ru/kopaonik/"
  parent = "serbia"
  weight = 1

[[main]]
  identifier = "about"
  name = "О нас"
  url = "/ru/about/"
  weight = 2

[[main]]
  identifier = "contact"
  name = "Контакты"
  url = "/ru/contact/"
  weight = 3
