[[main]]
  identifier = "serbia"
  name = "Srbija"
  url = "#"
  weight = 1

[[main]]
  identifier = "kopaonik"
  name = "Kopaonik"
  url = "/kopaonik/"
  parent = "serbia"
  weight = 1

[[main]]
  identifier = "about"
  name = "O Nama"
  url = "/about/"
  weight = 2

[[main]]
  identifier = "contact"
  name = "Kontakt"
  url = "/contact/"
  weight = 3
