[[main]]
  identifier = "airport-transfers"
  name = "Aerodromski Transferi"
  url = "/airport-transfers/"
  weight = 1

[[main]]
  identifier = "individual-transfers"
  name = "Individualni Transferi"
  url = "/individual-transfers/"
  weight = 2

[[main]]
  identifier = "group-transfers"
  name = "Grupni Transferi"
  url = "/group-transfers/"
  weight = 3

[[main]]
  identifier = "about"
  name = "O Nama"
  url = "/about/"
  weight = 4

[[main]]
  identifier = "contact"
  name = "Kontakt"
  url = "/contact/"
  weight = 5

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 6
