[[main]]
  identifier = "airport-transfers"
  name = "Airport Transfers"
  url = "/en/airport-transfers/"
  weight = 1

[[main]]
  identifier = "individual-transfers"
  name = "Individual Transfers"
  url = "/en/individual-transfers/"
  weight = 2

[[main]]
  identifier = "group-transfers"
  name = "Group Transfers"
  url = "/en/group-transfers/"
  weight = 3

[[main]]
  identifier = "about"
  name = "About"
  url = "/en/about/"
  weight = 4

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/en/contact/"
  weight = 5

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "/en/blog/"
  weight = 6
