[[main]]
  identifier = "slovenia"
  name = "Slovenija"
  url = "/slovenia/"
  weight = 1

[[main]]
  identifier = "bled"
  name = "Bled"
  url = "/slovenia/bled/"
  parent = "slovenia"
  weight = 1

[[main]]
  identifier = "celje"
  name = "Celje"
  url = "/slovenia/celje/"
  parent = "slovenia"
  weight = 2

[[main]]
  identifier = "izola"
  name = "Izola"
  url = "/slovenia/izola/"
  parent = "slovenia"
  weight = 3

[[main]]
  identifier = "koper"
  name = "Koper"
  url = "/slovenia/koper/"
  parent = "slovenia"
  weight = 4

[[main]]
  identifier = "kranj"
  name = "Kranj"
  url = "/slovenia/kranj/"
  parent = "slovenia"
  weight = 5

[[main]]
  identifier = "kranjska-gora"
  name = "Kranjska Gora"
  url = "/slovenia/kranjska-gora/"
  parent = "slovenia"
  weight = 6

[[main]]
  identifier = "ljubljana"
  name = "Ljubljana"
  url = "/slovenia/ljubljana/"
  parent = "slovenia"
  weight = 7

[[main]]
  identifier = "maribor"
  name = "Maribor"
  url = "/slovenia/maribor/"
  parent = "slovenia"
  weight = 8

[[main]]
  identifier = "novo-mesto"
  name = "Novo Mesto"
  url = "/slovenia/novo-mesto/"
  parent = "slovenia"
  weight = 9

[[main]]
  identifier = "piran"
  name = "Piran"
  url = "/slovenia/piran/"
  parent = "slovenia"
  weight = 10

[[main]]
  identifier = "portoroz"
  name = "Portorož"
  url = "/slovenia/portoroz/"
  parent = "slovenia"
  weight = 11

[[main]]
  identifier = "ptuj"
  name = "Ptuj"
  url = "/slovenia/ptuj/"
  parent = "slovenia"
  weight = 12

[[main]]
  identifier = "velenje"
  name = "Velenje"
  url = "/slovenia/velenje/"
  parent = "slovenia"
  weight = 13

[[main]]
  identifier = "croatia"
  name = "Hrvatska"
  url = "/croatia/"
  weight = 2

[[main]]
  identifier = "karlovac"
  name = "Karlovac"
  url = "/croatia/karlovac/"
  parent = "croatia"
  weight = 1

[[main]]
  identifier = "novigrad"
  name = "Novigrad"
  url = "/croatia/novigrad/"
  parent = "croatia"
  weight = 2

[[main]]
  identifier = "opatija"
  name = "Opatija"
  url = "/croatia/opatija/"
  parent = "croatia"
  weight = 3

[[main]]
  identifier = "porec"
  name = "Poreč"
  url = "/croatia/porec/"
  parent = "croatia"
  weight = 4

[[main]]
  identifier = "pula"
  name = "Pula"
  url = "/croatia/pula/"
  parent = "croatia"
  weight = 5

[[main]]
  identifier = "rijeka"
  name = "Rijeka"
  url = "/croatia/rijeka/"
  parent = "croatia"
  weight = 6

[[main]]
  identifier = "rovinj"
  name = "Rovinj"
  url = "/croatia/rovinj/"
  parent = "croatia"
  weight = 7

[[main]]
  identifier = "umag"
  name = "Umag"
  url = "/croatia/umag/"
  parent = "croatia"
  weight = 8

[[main]]
  identifier = "varazdin"
  name = "Varaždin"
  url = "/croatia/varazdin/"
  parent = "croatia"
  weight = 9

[[main]]
  identifier = "zagreb"
  name = "Zagreb"
  url = "/croatia/zagreb/"
  parent = "croatia"
  weight = 10

[[main]]
  identifier = "serbia"
  name = "Srbija"
  url = "/serbia/"
  weight = 3

[[main]]
  identifier = "kopaonik"
  name = "Kopaonik"
  url = "/serbia/kopaonik/"
  parent = "serbia"
  weight = 1

[[main]]
  identifier = "southern-shuttles"
  name = "Južni šatlovi"
  url = "/southern-shuttles/"
  weight = 4

[[main]]
  identifier = "cuprija"
  name = "Ćuprija"
  url = "/southern-shuttles/cuprija/"
  parent = "southern-shuttles"
  weight = 1

[[main]]
  identifier = "jagodina"
  name = "Jagodina"
  url = "/southern-shuttles/jagodina/"
  parent = "southern-shuttles"
  weight = 2

[[main]]
  identifier = "krusevac"
  name = "Kruševac"
  url = "/southern-shuttles/krusevac/"
  parent = "southern-shuttles"
  weight = 3

[[main]]
  identifier = "leskovac"
  name = "Leskovac"
  url = "/southern-shuttles/leskovac/"
  parent = "southern-shuttles"
  weight = 4

[[main]]
  identifier = "nis"
  name = "Niš"
  url = "/southern-shuttles/nis/"
  parent = "southern-shuttles"
  weight = 5

[[main]]
  identifier = "paracin"
  name = "Paraćin"
  url = "/southern-shuttles/paracin/"
  parent = "southern-shuttles"
  weight = 6

[[main]]
  identifier = "vranje"
  name = "Vranje"
  url = "/southern-shuttles/vranje/"
  parent = "southern-shuttles"
  weight = 7

[[main]]
  identifier = "airport-shuttles"
  name = "Aerodromski šatl"
  url = "/airport-shuttles/"
  weight = 5

[[main]]
  identifier = "belgrade-nikola-tesla"
  name = "Beograd (BEG)"
  url = "/airport-shuttles/belgrade-nikola-tesla/"
  parent = "airport-shuttles"
  weight = 1

[[main]]
  identifier = "nis-constantine-the-great"
  name = "Niš (INI)"
  url = "/airport-shuttles/nis-constantine-the-great/"
  parent = "airport-shuttles"
  weight = 2

[[main]]
  identifier = "craiova"
  name = "Advent Krajova"
  url = "/craiova/"
  weight = 6

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 7

[[main]]
  identifier = "about"
  name = "O Nama"
  url = "/about/"
  weight = 8

[[main]]
  identifier = "contact"
  name = "Kontakt"
  url = "/contact/"
  weight = 9